version: "3.9"
services:
  aobo:
    image: pt/aobo
    ports:
      - "80:82"
    volumes:
      - ./mount/data:/data
      - ./mount/etc/nginx:/etc/nginx
      - ./mount/etc/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./mount/etc/php.ini:/etc/php.ini
      - ./mount/etc/php-fpm.conf:/etc/php-fpm.conf
      - ./mount/etc/php-fpm.d:/etc/php-fpm.d
      - ./mount/var/log:/var/log
    restart: always
    # depends_on:
    #   - mysql
    #   - redis
    #   - memcached
    # network_mode: host
    networks:
      - net_group
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
  phpmyadmin:
    image: phpmyadmin:5-apache
    restart: always
    environment: 
      # - PMA_HOST=127.0.0.1
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_VERBOSE=TRUE
      - PMA_USER=root
      - PMA_PASSWORD=Geinshow2019
    ports:
      - "8080:80"
    networks:
      - net_group
    # network_mode: "service:aobo"

  mysql:
    image: mysql:5.7
    command: 
      - --default-authentication-plugin=mysql_native_password 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./mount/mysql:/var/lib/mysql
      - ./mount/etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: Geinshow2019
      MYSQL_DATABASE: outbook
      MYSQL_USER: outbook
      MYSQL_PASSWORD: secret
    # network_mode: host
    # network_mode: "service:aobo"
    networks:
      - net_group
  redis:
    image: "redis:alpine"
    restart: always
    command:
      - --appendonly yes
    volumes:
      - ./mount/redis:/data
    # network_mode: host
    # network_mode: "service:aobo"
    networks:
      - net_group
  memcached:
    image: "memcached:alpine"
    restart: always
    network_mode: "service:aobo"
    # network_mode: host
    # networks:
    #   - net_group

networks:
  net_group:


