version: "3.9"
services:
  php:
    image: pt/aobo
    ports:
      - "80:82"
      - "8080:8080"
    volumes:
      - ./mount/data:/data
      - ./mount/etc/nginx:/etc/nginx
      - ./mount/etc/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./mount/etc/php.ini:/etc/php.ini
      - ./mount/etc/php-fpm.conf:/etc/php-fpm.conf
      - ./mount/etc/php-fpm.d:/etc/php-fpm.d
      - ./mount/var/log:/var/log
      - ./mount/etc/phpMyAdmin:/etc/phpMyAdmin
    restart: always
    # depends_on:
    #   - mysql
    #   - redis
    #   - memcached
    # network_mode: host
    # networks:
      # - net_group
  mysql:
    image: mysql:5.7
    command: 
      - --default-authentication-plugin=mysql_native_password 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - ./mount/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Geinshow2019
    # network_mode: host
    network_mode: "service:php"
  redis:
    image: "redis:alpine"
    restart: always
    command:
      - --appendonly yes
    volumes:
      - ./mount/redis:/data
    # network_mode: host
    network_mode: "service:php"
  memcached:
    image: "memcached:alpine"
    restart: always
    network_mode: "service:php"
    # network_mode: host

# networks:
#   net_group:


